orgs:
  peerOrg1:
    name: peerOrg1
    mspid: Org1MSP
    domainName: org1.example.com
    peerLocations:
      peer0.org1.example.com: grpc://34.92.116.89:7051
      peer1.org1.example.com: grpc://34.92.116.89:7056
    ordererLocations:
      orderer.example.com: grpc://34.92.116.89:7050
    caName: ca0
    caLocation: http://34.92.116.89:7054
  peerOrg2:
    name: peerOrg2
    mspid: Org2MSP
    domainName: org2.example.com
    peerLocations:
      peer0.org2.example.com: grpc://34.92.116.89:8051
    ordererLocations:
      orderer.example.com: grpc://34.92.116.89:7050
    caLocation: http://34.92.116.89:8054

